from error.error import Error

class InvalidTaskReferenceError(Error):
    pass
